import { chromium } from "playwright-core";
const BASE = "http://localhost:1025";
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on("response", async r => {
  if (r.url().includes("/order/sale")) console.log("[resp]", r.status(), r.request().method(), r.url().split("8090").pop().slice(-40), (await r.text().catch(()=>"")).slice(0,200));
});
page.on("console", m => { if (m.type()==="error") console.log("[cerr]", m.text().slice(0,200)); });
await page.goto(BASE + "/login", { waitUntil: "networkidle" });
await page.fill('input[placeholder*="账号"]', "admin");
await page.fill('input[placeholder*="密码"]', "admin123");
await page.click(".login-button, .el-button--primary");
await page.waitForURL(u => !String(u).includes("/login"), { timeout: 20000 });
await page.evaluate(() => { Object.keys(localStorage).filter(k=>k.startsWith("saleDraft:")).forEach(k=>localStorage.removeItem(k)); });
await page.goto(BASE + "/order/sale-detail/index/", { waitUntil: "domcontentloaded" });
await page.waitForSelector(".split-workspace", { timeout: 20000 });
await page.waitForTimeout(1500);
const cascader = page.locator(".order-card .el-cascader").first();
await cascader.click(); await page.waitForTimeout(500);
await page.locator(".el-cascader-panel .el-cascader-node").first().hover(); await page.waitForTimeout(500);
await page.locator(".el-cascader-menu").nth(1).locator(".el-cascader-node").first().click();
await page.waitForTimeout(1200);
await page.keyboard.press("Escape"); await page.waitForTimeout(300);
await page.click(".right-tabs .el-tabs__item:has-text('常用')").catch(()=>{});
await page.waitForTimeout(500);
console.log("frequent items:", await page.locator(".frequent-item").count());
await page.locator(".frequent-item").first().click();
await page.waitForTimeout(800);
const row = page.locator(".order-card .vxe-body--row").first();
await row.locator("td").nth(4).dblclick(); await page.waitForTimeout(400);
const numInput = row.locator("td").nth(4).locator("input:visible").first();
await numInput.fill("10"); await numInput.press("Tab"); await page.waitForTimeout(400);
await row.locator("td").nth(5).dblclick(); await page.waitForTimeout(400);
const priceInput = row.locator("td").nth(5).locator("input:visible").first();
await priceInput.fill("88.88"); await priceInput.press("Tab"); await page.waitForTimeout(800);
console.log("row texts:", (await row.innerText()).replace(/\n/g, " | ").slice(0,200));
console.log("save buttons:", await page.locator("button:has-text('保存')").count());
const btn = page.locator(".order-card button:has-text('保存')").first();
console.log("btn visible:", await btn.isVisible().catch(()=>false), "disabled:", await btn.isDisabled().catch(()=>null));
await btn.click();
await page.waitForTimeout(4000);
console.log("messages:", await page.locator(".el-message").allTextContents());
console.log("msgbox:", await page.locator(".el-message-box__message").allTextContents());
console.log("form errors:", await page.locator(".el-form-item__error").allTextContents());
await page.screenshot({ path: "/tmp/save.png" });
await browser.close();
