package com.lin.distribution.service;

import java.util.List;

import com.lin.distribution.domain.DeliveryPrintConfigVersion;
import com.lin.distribution.dto.DeliveryPrintConfigDTO;
import com.lin.distribution.vo.DeliveryPrintConfigVO;

/**
 * 送货单打印拆分配置服务（W0-2.2，蓝图「送货单打印拆分配置/送货调整版本/自动结构恢复」）
 *
 * <p>为未打印送货单提供打印拆分/输出配置（拆分方式、介质、分页、打印顺序），
 * 每次保存写入一份可追溯的配置版本；支持一键恢复系统自动生成结构。
 * 规则约束：跨点合单仅 A4（针式仅单点）、针式单点固定每页 10 条。</p>
 *
 * @author dsh
 */
public interface DeliveryPrintConfigService {

    /**
     * 解析送货单当前打印配置（无配置时按批次组单策略推导默认值 + 自动生成结构，只读不落库）。
     *
     * @param deliveryOrderId 送货单ID
     * @return 打印配置响应
     */
    DeliveryPrintConfigVO resolveConfig(Long deliveryOrderId);

    /**
     * 保存打印配置（仅未打印 PENDING 单可改）：校验拆分/介质/分页规则与打印顺序全排列，
     * 写当前配置并追加一份版本记录（versionNo 自增）。
     *
     * @param deliveryOrderId 送货单ID
     * @param dto             保存请求
     * @return 更新后的打印配置响应
     */
    DeliveryPrintConfigVO saveConfig(Long deliveryOrderId, DeliveryPrintConfigDTO dto);

    /**
     * 查询送货单打印配置版本记录（最新在前）。
     *
     * @param deliveryOrderId 送货单ID
     * @return 版本记录集合
     */
    List<DeliveryPrintConfigVersion> listVersions(Long deliveryOrderId);

    /**
     * 恢复自动生成结构：按系统自动顺序（明细ID升序）重建打印结构，置 autoGenerated=true，
     * 追加一份版本记录（变更说明=恢复自动生成结构）。仅未打印 PENDING 单可恢复。
     *
     * @param deliveryOrderId 送货单ID
     * @return 恢复后的打印配置响应
     */
    DeliveryPrintConfigVO restoreAutoStructure(Long deliveryOrderId);
}
