package com.lin.distribution.service.impl;

import com.lin.common.exception.ServiceException;
import com.lin.distribution.constant.DeliveryOrderStatus;
import com.lin.distribution.domain.DeliveryOrder;
import com.lin.distribution.domain.DeliveryOrderDetail;
import com.lin.distribution.domain.DeliveryPrintConfig;
import com.lin.distribution.domain.DeliveryPrintConfigVersion;
import com.lin.distribution.dto.DeliveryPrintConfigDTO;
import com.lin.distribution.mapper.DeliveryOrderDetailMapper;
import com.lin.distribution.mapper.DeliveryOrderMapper;
import com.lin.distribution.mapper.DeliveryPrintConfigMapper;
import com.lin.distribution.mapper.DeliveryPrintConfigVersionMapper;
import com.lin.distribution.vo.DeliveryPrintConfigVO;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 送货单打印拆分配置测试（W0-2.2，蓝图「送货单打印拆分配置/送货调整版本/自动结构恢复」）
 *
 * <p>覆盖：无配置时按批次策略推导默认结构；仅未打印（PENDING）单可保存/恢复；
 * 跨点合单仅 A4（针式仅单点）校验；针式固定每页 10 条校验；打印顺序全排列校验；
 * 保存写版本记录；恢复自动结构重算顺序并追加版本。</p>
 */
@ExtendWith(MockitoExtension.class)
class DeliveryPrintConfigServiceImplTest {

    @Mock
    private DeliveryOrderMapper deliveryOrderMapper;
    @Mock
    private DeliveryOrderDetailMapper deliveryOrderDetailMapper;
    @Mock
    private DeliveryPrintConfigMapper configMapper;
    @Mock
    private DeliveryPrintConfigVersionMapper versionMapper;

    @InjectMocks
    private DeliveryPrintConfigServiceImpl service;

    private static final Long DELIVERY_ID = 10L;

    // ==================== resolveConfig ====================

    @Test
    void 无配置时按批次策略推导默认结构与自动排序() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(configMapper.selectByDeliveryOrderId(DELIVERY_ID)).thenReturn(null);
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(0);
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID))
                .thenReturn(Arrays.asList(detail(2L), detail(1L)));

        DeliveryPrintConfigVO vo = service.resolveConfig(DELIVERY_ID);

        assertEquals("DEFAULT_PER_DEPT", vo.getSplitMode());
        assertEquals("A4", vo.getMediaType());
        assertEquals(10, vo.getRowsPerPage());
        assertTrue(vo.getAutoGenerated());
        assertEquals(0, vo.getCurrentVersionNo());
        // autoOrder 按明细ID升序：1,2；2 条明细按每页10条 → 1 页
        assertEquals(Arrays.asList(1L, 2L), vo.getStructure().getOrder());
        assertEquals(1, vo.getStructure().getPages().size());
        assertEquals("第1/1张", vo.getStructure().getPages().get(0).getPageLabel());
        // 只读解析不落库
        verify(configMapper, never()).insertDeliveryPrintConfig(any());
    }

    @Test
    void 跨点总单默认推导为跨点合单() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "CUSTOMER_DATE"));
        when(configMapper.selectByDeliveryOrderId(DELIVERY_ID)).thenReturn(null);
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(0);
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID)).thenReturn(List.of());

        DeliveryPrintConfigVO vo = service.resolveConfig(DELIVERY_ID);

        assertEquals("CROSS_POINT_MERGE", vo.getSplitMode());
        assertEquals("A4", vo.getMediaType());
    }

    @Test
    void 送货单不存在时解析抛出异常() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID)).thenReturn(null);

        assertThrows(ServiceException.class, () -> service.resolveConfig(DELIVERY_ID));
    }

    @Test
    void 已保存配置时直接返回当前配置() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        DeliveryPrintConfig config = config(11L, DELIVERY_ID, "{\"order\":[5,6],\"pages\":[]}");
        when(configMapper.selectByDeliveryOrderId(DELIVERY_ID)).thenReturn(config);
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(3);

        DeliveryPrintConfigVO vo = service.resolveConfig(DELIVERY_ID);

        assertEquals(3, vo.getCurrentVersionNo());
        assertEquals(Arrays.asList(5L, 6L), vo.getStructure().getOrder());
    }

    // ==================== 规则校验 ====================

    @Test
    void 已打印送货单不可保存打印配置() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PRINTED.getCode(), "DELIVERY_POINT_DATE"));

        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.saveConfig(DELIVERY_ID, new DeliveryPrintConfigDTO()));

        assertTrue(ex.getMessage().contains("仅待打印"));
    }

    @Test
    void 跨点合单不允许针式输出() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "CUSTOMER_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID)).thenReturn(List.of(detail(1L), detail(2L)));

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setSplitMode("CROSS_POINT_MERGE");
        dto.setMediaType("DOT_MATRIX");

        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.saveConfig(DELIVERY_ID, dto));

        assertTrue(ex.getMessage().contains("跨配送点合单仅允许 A4"));
    }

    @Test
    void 单配送点按最大行数拆分允许针式输出() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID)).thenReturn(List.of(detail(1L)));
        when(configMapper.selectByDeliveryOrderIdForUpdate(DELIVERY_ID)).thenReturn(null);
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(0);

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setSplitMode("MAX_ROWS_SPLIT");
        dto.setMediaType("DOT_MATRIX");
        dto.setDetailOrder(List.of(1L));

        DeliveryPrintConfigVO vo = service.saveConfig(DELIVERY_ID, dto);

        assertEquals("MAX_ROWS_SPLIT", vo.getSplitMode());
        assertEquals("DOT_MATRIX", vo.getMediaType());
        assertEquals(10, vo.getRowsPerPage());
    }

    @Test
    void 针式打印固定每页10条() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID)).thenReturn(List.of(detail(1L), detail(2L)));

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setMediaType("DOT_MATRIX");
        dto.setRowsPerPage(20);

        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.saveConfig(DELIVERY_ID, dto));

        assertTrue(ex.getMessage().contains("针式打印固定每页 10 条"));
    }

    @Test
    void 打印顺序必须为该单有效明细全排列() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID))
                .thenReturn(Arrays.asList(detail(1L), detail(2L), detail(3L)));

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setDetailOrder(Arrays.asList(1L, 2L, 2L)); // 缺少3 + 重复2

        ServiceException ex = assertThrows(ServiceException.class,
                () -> service.saveConfig(DELIVERY_ID, dto));

        assertTrue(ex.getMessage().contains("必须包含该送货单全部"));
    }

    // ==================== 保存 ====================

    @Test
    void 保存配置写入当前配置并追加版本记录() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID))
                .thenReturn(Arrays.asList(detail(1L), detail(2L)));
        when(configMapper.selectByDeliveryOrderIdForUpdate(DELIVERY_ID)).thenReturn(null);
        // appendVersion 先读到 0 → 版本1；toVO 再读到 1
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(0, 1);

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setMediaType("A4");
        dto.setDetailOrder(Arrays.asList(2L, 1L));
        dto.setChangeNote("调整打印顺序");

        DeliveryPrintConfigVO vo = service.saveConfig(DELIVERY_ID, dto);

        ArgumentCaptor<DeliveryPrintConfig> configCaptor = ArgumentCaptor.forClass(DeliveryPrintConfig.class);
        verify(configMapper).insertDeliveryPrintConfig(configCaptor.capture());
        assertEquals("A4", configCaptor.getValue().getMediaType());
        assertFalse(configCaptor.getValue().getAutoGenerated());
        assertEquals(Arrays.asList(2L, 1L), configCaptor.getValue().getStructureJson() == null ? null
                : com.alibaba.fastjson2.JSON.parseObject(configCaptor.getValue().getStructureJson(),
                        com.lin.distribution.vo.DeliveryPrintStructure.class).getOrder());
        verify(configMapper, never()).updateDeliveryPrintConfig(any());

        // 版本记录 v1
        ArgumentCaptor<DeliveryPrintConfigVersion> verCaptor = ArgumentCaptor.forClass(DeliveryPrintConfigVersion.class);
        verify(versionMapper).insertDeliveryPrintConfigVersion(verCaptor.capture());
        assertEquals(1, verCaptor.getValue().getVersionNo());
        assertEquals("调整打印顺序", verCaptor.getValue().getChangeNote());

        assertEquals(1, vo.getCurrentVersionNo());
        assertEquals(Arrays.asList(2L, 1L), vo.getStructure().getOrder());
    }

    @Test
    void 保存时缺省打印顺序沿用当前结构顺序() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID))
                .thenReturn(Arrays.asList(detail(1L), detail(2L)));
        // 已有配置顺序 1,2
        when(configMapper.selectByDeliveryOrderIdForUpdate(DELIVERY_ID))
                .thenReturn(config(11L, DELIVERY_ID, "{\"order\":[1,2],\"pages\":[]}"));
        when(configMapper.selectByDeliveryOrderId(DELIVERY_ID))
                .thenReturn(config(11L, DELIVERY_ID, "{\"order\":[1,2],\"pages\":[]}"));
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(1);

        DeliveryPrintConfigDTO dto = new DeliveryPrintConfigDTO();
        dto.setMediaType("A4");

        service.saveConfig(DELIVERY_ID, dto);

        ArgumentCaptor<DeliveryPrintConfig> captor = ArgumentCaptor.forClass(DeliveryPrintConfig.class);
        verify(configMapper).updateDeliveryPrintConfig(captor.capture());
        assertEquals(Arrays.asList(1L, 2L),
                com.alibaba.fastjson2.JSON.parseObject(captor.getValue().getStructureJson(),
                        com.lin.distribution.vo.DeliveryPrintStructure.class).getOrder());
        verify(versionMapper).insertDeliveryPrintConfigVersion(any());
    }

    // ==================== 恢复自动结构 ====================

    @Test
    void 已送达送货单不可恢复自动结构() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.DELIVERED.getCode(), "DELIVERY_POINT_DATE"));

        assertThrows(ServiceException.class, () -> service.restoreAutoStructure(DELIVERY_ID));
    }

    @Test
    void 恢复自动结构按明细ID升序并追加版本() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(deliveryOrderDetailMapper.selectListByDeliveryId(DELIVERY_ID))
                .thenReturn(Arrays.asList(detail(3L), detail(1L), detail(2L)));
        // 已手工调整过（顺序 3,1,2 且 autoGenerated=false）
        DeliveryPrintConfig current = config(11L, DELIVERY_ID, "{\"order\":[3,1,2],\"pages\":[]}");
        current.setMediaType("DOT_MATRIX");
        current.setRowsPerPage(10);
        current.setAutoGenerated(Boolean.FALSE);
        when(configMapper.selectByDeliveryOrderId(DELIVERY_ID)).thenReturn(current);
        when(configMapper.selectByDeliveryOrderIdForUpdate(DELIVERY_ID)).thenReturn(current);
        // appendVersion 先读到 2 → 版本3；toVO 再读到 3
        when(versionMapper.selectMaxVersionNo(DELIVERY_ID)).thenReturn(2, 3);

        DeliveryPrintConfigVO vo = service.restoreAutoStructure(DELIVERY_ID);

        ArgumentCaptor<DeliveryPrintConfig> captor = ArgumentCaptor.forClass(DeliveryPrintConfig.class);
        verify(configMapper).updateDeliveryPrintConfig(captor.capture());
        assertTrue(captor.getValue().getAutoGenerated());
        assertEquals(Arrays.asList(1L, 2L, 3L),
                com.alibaba.fastjson2.JSON.parseObject(captor.getValue().getStructureJson(),
                        com.lin.distribution.vo.DeliveryPrintStructure.class).getOrder());

        ArgumentCaptor<DeliveryPrintConfigVersion> verCaptor = ArgumentCaptor.forClass(DeliveryPrintConfigVersion.class);
        verify(versionMapper).insertDeliveryPrintConfigVersion(verCaptor.capture());
        assertEquals(3, verCaptor.getValue().getVersionNo());
        assertEquals("恢复自动生成结构", verCaptor.getValue().getChangeNote());
        assertTrue(verCaptor.getValue().getAutoGenerated());

        assertEquals(3, vo.getCurrentVersionNo());
        assertTrue(vo.getAutoGenerated());
    }

    // ==================== listVersions ====================

    @Test
    void 查询版本列表() {
        when(deliveryOrderMapper.selectDeliveryOrderById(DELIVERY_ID))
                .thenReturn(delivery(DELIVERY_ID, "HS202608280001", DeliveryOrderStatus.PENDING.getCode(), "DELIVERY_POINT_DATE"));
        when(versionMapper.selectByDeliveryOrderId(DELIVERY_ID))
                .thenReturn(List.of(version(2L, 2), version(1L, 1)));

        List<DeliveryPrintConfigVersion> versions = service.listVersions(DELIVERY_ID);

        assertEquals(2, versions.size());
        assertEquals(2, versions.get(0).getVersionNo());
    }

    // ==================== 测试数据 ====================

    private DeliveryOrder delivery(Long id, String code, Integer status, String scopeType) {
        DeliveryOrder delivery = new DeliveryOrder();
        delivery.setId(id);
        delivery.setCode(code);
        delivery.setStatus(status);
        delivery.setScopeType(scopeType);
        return delivery;
    }

    private DeliveryOrderDetail detail(Long id) {
        DeliveryOrderDetail detail = new DeliveryOrderDetail();
        detail.setId(id);
        detail.setDeliveryId(DELIVERY_ID);
        detail.setIsDeleted(false);
        return detail;
    }

    private DeliveryPrintConfig config(Long id, Long deliveryOrderId, String structureJson) {
        DeliveryPrintConfig config = new DeliveryPrintConfig();
        config.setId(id);
        config.setDeliveryOrderId(deliveryOrderId);
        config.setSplitMode("DEFAULT_PER_DEPT");
        config.setMediaType("A4");
        config.setRowsPerPage(10);
        config.setStructureJson(structureJson);
        config.setAutoGenerated(true);
        config.setIsDeleted(false);
        return config;
    }

    private DeliveryPrintConfigVersion version(Long id, Integer no) {
        DeliveryPrintConfigVersion version = new DeliveryPrintConfigVersion();
        version.setId(id);
        version.setDeliveryOrderId(DELIVERY_ID);
        version.setVersionNo(no);
        return version;
    }
}
