<template>
  <div>
    demo page
    <el-button @click="handleClick">打印预览</el-button>
    <Preview ref="printPreiew" />
  </div>
</template>

<script>
import { disAutoConnect, hiprint } from "@sv-print/hiprint";
import "sv-print/dist/style.css"; // sv-print 样式

import Preview from "@/components/PrintDesigner/preview.vue";

export default {
  name: "Demo",
  components: { Preview },
  data() {
    return {
      hiprintTemplate: null,
      template: {
        panels: [
          {
            name: 1,
            index: 0,
            width: 140,
            height: 216,
            paperFooter: 526.5,
            paperHeader: 62,
            printElements: [
              {
                options: {
                  top: 21,
                  left: 129,
                  title: "送货单",
                  width: 120,
                  height: 17,
                  fontSize: 16.5,
                  testData: "送货单",
                  hideTitle: true,
                  textAlign: "center",
                  fontFamily: "SimSun",
                  fontWeight: "700",
                },
                printElementType: { type: "text", title: "送货单" },
              },
              {
                options: {
                  qid: "customerDeptName",
                  top: 45,
                  left: 6,
                  color: "#000000",
                  field: "customerDeptName",
                  title: "客户",
                  width: 120,
                  height: 16,
                  fontSize: 9.75,
                  testData: "xxxx公司",
                  fontFamily: "SimSun",
                  fontWeight: "600",
                  qrCodeLevel: 0,
                  coordinateSync: false,
                  widthHeightSync: false,
                  textContentVerticalAlign: "middle",
                },
                printElementType: { type: "text", title: "客户" },
              },
              {
                options: {
                  qid: "deliveryDate",
                  top: 45,
                  left: 300,
                  color: "#000000",
                  field: "deliveryDate",
                  title: "日期",
                  width: 90,
                  height: 16,
                  fontSize: 9.75,
                  testData: "2024.01.01",
                  fontFamily: "SimSun",
                  fontWeight: "600",
                  qrCodeLevel: 0,
                  coordinateSync: false,
                  widthHeightSync: false,
                  textContentVerticalAlign: "middle",
                },
                printElementType: { type: "text", title: "日期" },
              },
              {
                options: {
                  top: 64.5,
                  left: 3,
                  field: "table",
                  width: 387,
                  fields: [
                    { text: "序号", field: "index" },
                    { text: "商品名称", field: "productName" },
                    { text: "单位", field: "productUnit" },
                    { text: "计划数量", field: "num" },
                    { text: "实收数量", field: "actualNum" },
                    { text: "单价", field: "productPrice" },
                    { text: "金额", field: "expectAmount" },
                  ],
                  height: 76.5,
                  columns: [
                    [
                      {
                        align: "center",
                        field: "index",
                        fixed: false,
                        title: "序号",
                        width: 27.642857142857135,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "index",
                        titleSync: false,
                        tableSummary: "",
                        tableTextType: "sequence",
                        tableQRCodeLevel: 0,
                        tableSummaryText: "小计",
                        tableSummaryAlign: "left",
                        tableSummaryTitle: true,
                        tableSummaryColspan: "6",
                      },
                      {
                        align: "center",
                        field: "productName",
                        fixed: false,
                        title: "商品名称",
                        width: 110.57142857142854,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "productName",
                        tableSummary: "",
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "productUnit",
                        fixed: false,
                        title: "单位",
                        width: 27.642857142857135,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "productUnit",
                        tableSummary: "",
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "num",
                        fixed: false,
                        title: "计划数量",
                        width: 55.28571428571429,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "num",
                        titleSync: false,
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableSummary: "",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "actualNum",
                        fixed: false,
                        title: "实收数量",
                        width: 55.28571428571429,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "actualNum",
                        titleSync: false,
                        formatter2:
                          "function(value,row,index,options){ return ''; }",
                        tableSummary: "",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "productPrice",
                        fixed: false,
                        title: "单价",
                        width: 55.28571428571429,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "productPrice",
                        titleSync: false,
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableSummary: "",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "expectAmount",
                        fixed: false,
                        title: "金额",
                        width: 55.28571428571429,
                        checked: true,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "expectAmount",
                        titleSync: false,
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableSummary: "sum",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: false,
                        tableSummaryColspan: "0",
                      },
                      {
                        align: "center",
                        field: "productSpec",
                        fixed: false,
                        title: "规格",
                        width: 20,
                        checked: false,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "productSpec",
                      },
                      {
                        align: "center",
                        field: "remark",
                        fixed: false,
                        title: "备注",
                        width: 20,
                        checked: false,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "remark",
                      },
                      {
                        align: "center",
                        field: "TM",
                        fixed: false,
                        title: "条码",
                        width: 25,
                        checked: false,
                        colspan: 1,
                        rowspan: 1,
                        columnId: "TM",
                      },
                    ],
                  ],
                  coordinateSync: false,
                  widthHeightSync: false,
                  tableFooterRepeat: "last",
                  tableHeaderRepeat: "page",
                  gridColumnsFooterFormatter:
                    'function gridColumnsFooterFormatter(options, rows, data, pageData) {\n        if (data) {\n          // 设置自定义内容，id 为 custom-grid-footer\n          var textContent = "\\n                    <div id=\\"custom-grid-footer\\"; style=\\"display: flex; justify-content: space-between; padding-top: 8px; font-size: 11pt; font-weight: bold; font-family: \'SimSun\'\\">\\n                        <sapn>\\u6536\\u8D27\\u5355\\u4F4D\\uFF1A</sapn>\\n                        <sapn>\\u9001\\u8D27\\u5355\\u4F4D\\uFF1A".concat(data.deliveryName || "", "</sapn>\\n                    </div>\\n                ");\n          // 遍历 elements 并替换内容\n          var elements = document.getElementsByClassName("hiprint-gridColumnsFooter");\n          for (var i = 0; i < elements.length; i++) {\n            var element = elements[i];\n            element.innerHTML = textContent;\n          }\n          return textContent;\n        }\n        return "自定义表尾内容";\n      }',
                },
                printElementType: {
                  type: "table",
                  title: "送货表格",
                  editable: true,
                  columnResizable: true,
                  isEnableDeleteRow: true,
                  isEnableEditField: true,
                  isEnableInsertRow: true,
                  isEnableMergeCell: true,
                  columnAlignEditable: true,
                  columnTitleEditable: true,
                  isEnableContextMenu: true,
                  isEnableDeleteColumn: true,
                  isEnableInsertColumn: true,
                  columnDisplayEditable: true,
                  columnDisplayIndexEditable: true,
                },
              },
            ],
            paperNumberTop: 590,
            paperNumberLeft: 366,
            overPrintOptions: {},
            watermarkOptions: {},
            paperNumberContinue: true,
          },
        ],
      },
      template1: {
        panels: [
          {
            index: 0,
            name: 1,
            height: 216,
            width: 140,
            paperHeader: 62,
            paperFooter: 526.5,
            printElements: [
              {
                options: {
                  left: 129,
                  top: 21,
                  height: 17,
                  width: 120,
                  title: "送货单",
                  fontSize: 16.5,
                  testData: "送货单",
                  hideTitle: true,
                  textAlign: "center",
                  fontFamily: "SimSun",
                  fontWeight: "700",
                },
                printElementType: {
                  title: "送货单",
                  type: "text",
                },
              },
              {
                options: {
                  left: 6,
                  top: 45,
                  height: 16,
                  width: 120,
                  qid: "customerDeptName",
                  color: "#000000",
                  field: "customerDeptName",
                  title: "客户",
                  fontSize: 9.75,
                  testData: "xxxx公司",
                  fontFamily: "SimSun",
                  fontWeight: "600",
                  qrCodeLevel: 0,
                  coordinateSync: false,
                  widthHeightSync: false,
                  textContentVerticalAlign: "middle",
                },
                printElementType: {
                  title: "客户",
                  type: "text",
                },
              },
              {
                options: {
                  left: 300,
                  top: 45,
                  height: 16,
                  width: 90,
                  qid: "deliveryDate",
                  color: "#000000",
                  field: "deliveryDate",
                  title: "日期",
                  fontSize: 9.75,
                  testData: "2024.01.01",
                  fontFamily: "SimSun",
                  fontWeight: "600",
                  qrCodeLevel: 0,
                  coordinateSync: false,
                  widthHeightSync: false,
                  textContentVerticalAlign: "middle",
                },
                printElementType: {
                  title: "日期",
                  type: "text",
                },
              },
              {
                options: {
                  left: 3,
                  top: 64.5,
                  height: 87,
                  width: 387,
                  field: "table",
                  fields: [
                    {
                      text: "序号",
                      field: "index",
                    },
                    {
                      text: "商品名称",
                      field: "productName",
                    },
                    {
                      text: "单位",
                      field: "productUnit",
                    },
                    {
                      text: "计划数量",
                      field: "num",
                    },
                    {
                      text: "实收数量",
                      field: "actualNum",
                    },
                    {
                      text: "单价",
                      field: "productPrice",
                    },
                    {
                      text: "金额",
                      field: "expectAmount",
                    },
                  ],
                  coordinateSync: false,
                  widthHeightSync: false,
                  tableFooterRepeat: "last",
                  tableHeaderRepeat: "page",
                  gridColumnsFooterFormatter:
                    'function gridColumnsFooterFormatter(options, rows, data, pageData) {\n        if (data) {\n          // 设置自定义内容，id 为 custom-grid-footer\n          var textContent = "\\n                    <div id=\\"custom-grid-footer\\"; style=\\"display: flex; justify-content: space-between; padding-top: 8px; font-size: 11pt; font-weight: bold; font-family: \'SimSun\'\\">\\n                        <sapn>\\u6536\\u8D27\\u5355\\u4F4D\\uFF1A</sapn>\\n                        <sapn>\\u9001\\u8D27\\u5355\\u4F4D\\uFF1A".concat(data.deliveryName || "", "</sapn>\\n                    </div>\\n                ");\n          // 遍历 elements 并替换内容\n          var elements = document.getElementsByClassName("hiprint-gridColumnsFooter");\n          for (var i = 0; i < elements.length; i++) {\n            var element = elements[i];\n            element.innerHTML = textContent;\n          }\n          return textContent;\n        }\n        return "自定义表尾内容";\n      }',
                  columns: [
                    [
                      {
                        width: 27.642857142857135,
                        checked: true,
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                      },
                      {
                        width: 110.57142857142854,
                        title: "分组1",
                        titleSync: false,
                        checked: true,
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummary: "",
                      },
                      {
                        width: 27.642857142857135,
                        title: "分组2",
                        titleSync: false,
                        checked: true,
                        fixed: false,
                        rowspan: 1,
                        colspan: 2,
                        align: "center",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummary: "",
                      },
                      {
                        width: 55.28571428571429,
                        title: "分组3",
                        titleSync: false,
                        checked: true,
                        fixed: false,
                        rowspan: 1,
                        colspan: 3,
                        align: "center",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummary: "",
                      },
                    ],
                    [
                      {
                        width: 27.642857142857135,
                        title: "序号",
                        titleSync: false,
                        field: "index",
                        checked: true,
                        columnId: "index",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        tableTextType: "sequence",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryText: "小计",
                        tableSummaryColspan: "6",
                        tableSummary: "",
                        tableSummaryAlign: "left",
                      },
                      {
                        width: 110.57142857142854,
                        title: "商品名称",
                        field: "productName",
                        checked: true,
                        columnId: "productName",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                        tableSummary: "",
                      },
                      {
                        width: 27.642857142857135,
                        title: "单位",
                        field: "productUnit",
                        checked: true,
                        columnId: "productUnit",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                        tableSummary: "",
                      },
                      {
                        width: 55.28571428571429,
                        title: "计划数量",
                        titleSync: false,
                        field: "num",
                        checked: true,
                        columnId: "num",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                        tableSummary: "",
                      },
                      {
                        width: 55.28571428571429,
                        title: "实收数量",
                        titleSync: false,
                        field: "actualNum",
                        checked: true,
                        columnId: "actualNum",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        formatter2:
                          "function(value,row,index,options){ return ''; }",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                        tableSummary: "",
                      },
                      {
                        width: 55.28571428571429,
                        title: "单价",
                        titleSync: false,
                        field: "productPrice",
                        checked: true,
                        columnId: "productPrice",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: true,
                        tableSummaryColspan: "0",
                        tableSummary: "",
                      },
                      {
                        width: 55.28571428571429,
                        title: "金额",
                        titleSync: false,
                        field: "expectAmount",
                        checked: true,
                        columnId: "expectAmount",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                        formatter2:
                          "function(value, row, index, options) {\n    const numericValue = parseFloat(value);\n    if (!isNaN(numericValue)) {\n        return numericValue.toFixed(2);\n    } else {\n        return value;\n    }\n}",
                        tableQRCodeLevel: 0,
                        tableSummaryTitle: false,
                        tableSummaryColspan: "0",
                        tableSummary: "sum",
                      },
                    ],
                  ],
                },
                printElementType: {
                  title: "送货表格",
                  type: "table",
                  editable: true,
                  columnDisplayEditable: true,
                  columnDisplayIndexEditable: true,
                  columnTitleEditable: true,
                  columnResizable: true,
                  columnAlignEditable: true,
                  isEnableEditField: true,
                  isEnableContextMenu: true,
                  isEnableInsertRow: true,
                  isEnableDeleteRow: true,
                  isEnableInsertColumn: true,
                  isEnableDeleteColumn: true,
                  isEnableMergeCell: true,
                },
              },
            ],
            paperNumberLeft: 366,
            paperNumberTop: 590,
            paperNumberContinue: true,
            overPrintOptions: {},
            watermarkOptions: {},
          },
        ],
      },
      printData: {
        table: [
          {
            index: 1,
            productName: "测试商品01",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 2,
            productName: "测试商品02",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 3,
            productName: "测试商品03",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 4,
            productName: "测试商品04",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 5,
            productName: "测试商品05",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 6,
            productName: "测试商品06",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 7,
            productName: "测试商品07",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 8,
            productName: "测试商品08",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 9,
            productName: "测试商品09",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 10,
            productName: "测试商品10",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 11,
            productName: "测试商品11",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 12,
            productName: "测试商品12",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 13,
            productName: "测试商品13",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 14,
            productName: "测试商品14",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 15,
            productName: "测试商品15",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 16,
            productName: "测试商品16",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 17,
            productName: "测试商品17",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 18,
            productName: "测试商品18",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 19,
            productName: "测试商品19",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 20,
            productName: "测试商品20",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 21,
            productName: "测试商品21",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 22,
            productName: "测试商品22",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 23,
            productName: "测试商品23",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 24,
            productName: "测试商品24",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 25,
            productName: "测试商品25",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 26,
            productName: "测试商品26",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 27,
            productName: "测试商品27",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 28,
            productName: "测试商品28",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 29,
            productName: "测试商品29",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 30,
            productName: "测试商品30",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
        ],
      },
    };
  },
  mounted() {
    // 取消自动连接
    disAutoConnect();
  },
  methods: {
    handleClick() {
      let hiprintTemplate = new hiprint.PrintTemplate({
        template: this.template1,
      });

      const $printPreiew = this.$refs.printPreiew;

      $printPreiew.show(hiprintTemplate, this.printData);
    },
  },
};
</script>
