<template>
  <div>
    demo page
    <el-button @click="handleClick">打印预览</el-button>
    <Preview ref="printPreiew" />
  </div>
</template>

<script>
import { disAutoConnect, autoConnect, hiprint } from "@sv-print/hiprint";
import "sv-print/dist/style.css"; // sv-print 样式

import Preview from "@/components/PrintDesigner/preview.vue";

export default {
  name: "Demo",
  components: { Preview },
  data() {
    return {
      hiprintTemplate: null,
      template: {
        panels: [
          {
            name: null,
            height: 216,
            width: 140,
            paperHeader: 62,
            paperFooter: 526.5,
            printElements: [
              {
                options: {
                  left: 129,
                  top: 21,
                  height: 17,
                  width: 120,
                  testData: "送货单",
                  fontSize: 16.5,
                  fontWeight: "700",
                  textAlign: "center",
                  hideTitle: true,
                  fontFamily: "SimSun",
                  title: "送货单",
                },
                printElementType: {
                  title: "送货单",
                  type: "text",
                },
              },
              {
                options: {
                  left: 6,
                  top: 45,
                  height: 16,
                  width: 120,
                  field: "customerDeptName",
                  testData: "xxxx公司",
                  fontSize: 9.75,
                  fontWeight: "600",
                  textAlign: "left",
                  textContentVerticalAlign: "middle",
                  fontFamily: "SimSun",
                  title: "客户",
                  qid: "customerDeptName",
                  right: 120.75,
                  bottom: 61,
                  vCenter: 60.75,
                  hCenter: 53,
                },
                printElementType: {
                  title: "客户",
                  type: "text",
                },
              },
              {
                options: {
                  left: 300,
                  top: 45,
                  height: 16,
                  width: 90,
                  field: "deliveryDate",
                  testData: "2024.01.01",
                  fontSize: 9.75,
                  fontWeight: "600",
                  textAlign: "left",
                  textContentVerticalAlign: "middle",
                  fontFamily: "SimSun",
                  title: "日期",
                  qid: "deliveryDate",
                  right: 388.5,
                  bottom: 60.25,
                  vCenter: 343.5,
                  hCenter: 52.25,
                },
                printElementType: {
                  title: "日期",
                  type: "text",
                },
              },
              {
                options: {
                  left: 3,
                  top: 64.5,
                  height: 54,
                  width: 387,
                  tableFooterRepeat: "last",
                  fields: [
                    {
                      text: "序号",
                      field: "index",
                    },
                    {
                      text: "商品名称",
                      field: "productName",
                    },
                    {
                      text: "单位",
                      field: "productUnit",
                    },
                    {
                      text: "计划数量",
                      field: "num",
                    },
                    {
                      text: "实收数量",
                      field: "actualNum",
                    },
                    {
                      text: "单价",
                      field: "productPrice",
                    },
                    {
                      text: "金额",
                      field: "expectAmount",
                    },
                  ],
                  field: "table",
                  tableHeaderRepeat: "page",
                  footerFormatter:
                    'function footerFormatter(options, rows, data, currentPageGridRowsData) {\n    console.log(\'footer data\', data, \'options\', options, \'rows\', rows, \'currentPageGridRowsData\',\n        currentPageGridRowsData);\n    if (data && data["totalCap"]) {\n        return "<td style=\\"padding:0 10px\\" colspan=\\"100\\">".concat("小计: " + data["totalCap"], "</td>");\n    }\n    return \'<td style="padding:0 10px" colspan="100">小计: </td><br/><span>送货单位</span>\';\n}',
                  qid: "table",
                  right: 390,
                  bottom: 118.5000057220459,
                  vCenter: 196.5,
                  hCenter: 91.5000057220459,
                  coordinateSync: false,
                  widthHeightSync: false,
                  columns: [
                    [
                      {
                        width: 27.642857142857135,
                        title: "序号",
                        field: "index",
                        checked: true,
                        columnId: "index",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 110.29917857142856,
                        title: "商品名称",
                        field: "productName",
                        checked: true,
                        columnId: "productName",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 28.03360714285713,
                        title: "单位",
                        field: "productUnit",
                        checked: true,
                        columnId: "productUnit",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 55.167214285714294,
                        title: "计划数量",
                        field: "num",
                        checked: true,
                        columnId: "num",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 55.28571428571427,
                        title: "实收数量",
                        field: "actualNum",
                        checked: true,
                        columnId: "actualNum",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 54.8102142857143,
                        title: "单价",
                        field: "productPrice",
                        checked: true,
                        columnId: "productPrice",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 55.76121428571425,
                        title: "金额",
                        field: "expectAmount",
                        checked: true,
                        columnId: "expectAmount",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 20,
                        title: "规格",
                        field: "productSpec",
                        checked: false,
                        columnId: "productSpec",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                      {
                        width: 25,
                        title: "条码",
                        field: "TM",
                        checked: false,
                        columnId: "TM",
                        fixed: false,
                        rowspan: 1,
                        colspan: 1,
                        align: "center",
                      },
                    ],
                  ],
                },
                printElementType: {
                  title: "送货表格",
                  type: "table",
                  editable: true,
                  columnDisplayEditable: true,
                  columnDisplayIndexEditable: true,
                  columnTitleEditable: true,
                  columnResizable: true,
                  columnAlignEditable: true,
                  isEnableEditField: true,
                  isEnableContextMenu: true,
                  isEnableInsertRow: true,
                  isEnableDeleteRow: true,
                  isEnableInsertColumn: true,
                  isEnableDeleteColumn: true,
                  isEnableMergeCell: true,
                },
              },
              {
                options: {
                  left: 270,
                  top: 531,
                  height: 16,
                  width: 120,
                  testData: "aaaa公司",
                  fontSize: 9.75,
                  fontWeight: "600",
                  textAlign: "left",
                  textContentVerticalAlign: "middle",
                  fontFamily: "SimSun",
                  title: "送货单位",
                  right: 390.0000228881836,
                  bottom: 547.0000114440918,
                  vCenter: 330.0000228881836,
                  hCenter: 539.0000114440918,
                  coordinateSync: false,
                  widthHeightSync: false,
                  qrCodeLevel: 0,
                },
                printElementType: {
                  title: "送货单位",
                  type: "text",
                },
              },
              {
                options: {
                  left: 6,
                  top: 531,
                  height: 16,
                  width: 120,
                  testData: "xxxx公司",
                  fontSize: 9.75,
                  fontWeight: "600",
                  textAlign: "left",
                  textContentVerticalAlign: "middle",
                  fontFamily: "SimSun",
                  title: "收货单位",
                  coordinateSync: false,
                  widthHeightSync: false,
                  qrCodeLevel: 0,
                  right: 126,
                  bottom: 546.2500171661377,
                  vCenter: 66,
                  hCenter: 538.2500171661377,
                },
                printElementType: {
                  title: "送货单位",
                  type: "text",
                },
              },
            ],
            paperNumberLeft: 366,
            paperNumberTop: 590,
            paperNumberContinue: true,
            watermarkOptions: {},
            panelLayoutOptions: {},
          },
        ],
      },
      printData: {
        table: [
          {
            index: 1,
            productName: "测试商品01",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 2,
            productName: "测试商品02",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 3,
            productName: "测试商品03",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 4,
            productName: "测试商品04",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 5,
            productName: "测试商品05",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 6,
            productName: "测试商品06",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 7,
            productName: "测试商品07",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 8,
            productName: "测试商品08",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 9,
            productName: "测试商品09",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 10,
            productName: "测试商品10",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 11,
            productName: "测试商品11",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 12,
            productName: "测试商品12",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 13,
            productName: "测试商品13",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 14,
            productName: "测试商品14",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 15,
            productName: "测试商品15",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 16,
            productName: "测试商品16",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 17,
            productName: "测试商品17",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 18,
            productName: "测试商品18",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 19,
            productName: "测试商品19",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 20,
            productName: "测试商品20",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 21,
            productName: "测试商品21",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 22,
            productName: "测试商品22",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 23,
            productName: "测试商品23",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 24,
            productName: "测试商品24",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 25,
            productName: "测试商品25",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 26,
            productName: "测试商品26",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 27,
            productName: "测试商品27",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 28,
            productName: "测试商品28",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 29,
            productName: "测试商品29",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
          {
            index: 30,
            productName: "测试商品30",
            num: 2,
            productUnit: "斤",
            productSpec: "1*24g",
            TM: "2O22010100110",
            productPrice: "6.8",
            expectAmount: "13.6",
          },
        ],
      },
    };
  },
  mounted() {
    // 取消自动连接
    disAutoConnect();
  },
  methods: {
    handleClick() {
      let hiprintTemplate = new hiprint.PrintTemplate({
        template: this.template,
      });

      const $printPreiew = this.$refs.printPreiew;

      $printPreiew.show(hiprintTemplate, this.printData);
    },
  },
};
</script>
