package com.lin.distribution.vo;

import com.lin.distribution.domain.DeliveryPrintConfig;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 送货单打印拆分配置响应（W0-2.2）
 *
 * <p>包含当前配置、解析后的打印结构、送货单基本信息与当前版本号，
 * 供送货单打印配置页展示与调整。</p>
 *
 * @author dsh
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DeliveryPrintConfigVO {

    /** 送货单ID */
    private Long deliveryOrderId;

    /** 送货单编号 */
    private String code;

    /** 送货单状态（0待打印/1已打印/2已送达/3已作废） */
    private Integer deliveryStatus;

    /** 当前配置版本序号（无版本则为 0） */
    private Integer currentVersionNo;

    /** 拆分方式 */
    private String splitMode;

    /** 输出介质 */
    private String mediaType;

    /** 分页行数 */
    private Integer rowsPerPage;

    /** 当前结构是否为系统自动生成 */
    private Boolean autoGenerated;

    /** 打印结构（解析后） */
    private DeliveryPrintStructure structure;

    /** 乐观锁版本号 */
    private Integer version;

    /**
     * 由配置领域对象 + 额外信息构建 VO。
     */
    public static DeliveryPrintConfigVO from(DeliveryPrintConfig config, String code, Integer deliveryStatus,
                                             Integer currentVersionNo) {
        DeliveryPrintConfigVO vo = new DeliveryPrintConfigVO();
        vo.deliveryOrderId = config.getDeliveryOrderId();
        vo.code = code;
        vo.deliveryStatus = deliveryStatus;
        vo.currentVersionNo = currentVersionNo == null ? 0 : currentVersionNo;
        vo.splitMode = config.getSplitMode();
        vo.mediaType = config.getMediaType();
        vo.rowsPerPage = config.getRowsPerPage();
        vo.autoGenerated = config.getAutoGenerated();
        vo.structure = DeliveryPrintStructure.fromJson(config.getStructureJson());
        vo.version = config.getVersion();
        return vo;
    }
}
