package com.lin.distribution.domain;

import com.lin.common.core.domain.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;

/**
 * 送货单打印配置版本记录对象 t_delivery_print_config_version
 *
 * <p>W0-2.2（蓝图「送货调整版本/自动结构恢复/配置变更必须审计」）：
 * 未打印送货单的排序、拆分、合并每次保存为一份可追溯的打印配置版本快照，
 * 记录操作人/时间/来源是否为自动结构/变更说明，供审计与一键恢复自动生成结构。</p>
 *
 * @author dsh
 */
@EqualsAndHashCode(callSuper = true)
@Data
@Builder
@AllArgsConstructor
@RequiredArgsConstructor
public class DeliveryPrintConfigVersion extends BaseEntity {
    private static final long serialVersionUID = 1L;

    /** 主键 */
    private Long id;

    /** 送货单ID */
    private Long deliveryOrderId;

    /** 版本序号（同一送货单内自增，从 1 起） */
    private Integer versionNo;

    /** 拆分方式（快照，与当前配置同语义） */
    private String splitMode;

    /** 输出介质（快照） */
    private String mediaType;

    /** 分页行数（快照） */
    private Integer rowsPerPage;

    /** 打印结构 JSON（快照） */
    private String structureJson;

    /** 该版本是否系统自动生成结构（1=是，0=手工调整） */
    private Boolean autoGenerated;

    /** 变更说明（恢复自动结构固定为「恢复自动生成结构」） */
    private String changeNote;

}
