package com.lin.distribution.domain;

import com.baomidou.mybatisplus.annotation.Version;
import com.lin.common.core.domain.BaseEntity;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.RequiredArgsConstructor;

/**
 * 送货单打印拆分配置对象 t_delivery_print_config
 *
 * <p>W0-2.2（蓝图「送货单打印拆分配置」）：记录一张送货单的打印拆分/输出配置，
 * 与批量组单策略快照解耦——同一配送日期批次可对具体送货单单独调整打印顺序、分页与介质。
 * 核心规则由 {@link com.lin.distribution.constant.DeliveryPrintRule} 约束：
 * 跨点合单仅 A4、针式仅单点每页 10 条。每次保存写一份版本记录（t_delivery_print_config_version），
 * 提供“恢复自动生成结构”。</p>
 *
 * @author dsh
 */
@EqualsAndHashCode(callSuper = true)
@Data
@Builder
@AllArgsConstructor
@RequiredArgsConstructor
public class DeliveryPrintConfig extends BaseEntity {
    private static final long serialVersionUID = 1L;

    /** 主键 */
    private Long id;

    /** 送货单ID（唯一，一张送货单一份当前配置） */
    private Long deliveryOrderId;

    /** 拆分方式：DEFAULT_PER_DEPT/CROSS_POINT_MERGE/MAX_ROWS_SPLIT */
    private String splitMode;

    /** 输出介质：A4/DOT_MATRIX */
    private String mediaType;

    /** 分页行数（针式单点固定 10；A4 按页高自动分页，仅记录期望值） */
    private Integer rowsPerPage;

    /** 打印结构 JSON（升序明细ID序列 + 分页桶，含“第N/M张”） */
    private String structureJson;

    /** 当前结构是否为系统自动生成（false=手工调整；恢复自动结构后置 true） */
    private Boolean autoGenerated;

    /** 版本号（乐观锁） */
    @Version
    private Integer version;

    /** 逻辑删除 */
    private Boolean isDeleted;

}
