-- add sys_menu item
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类',4,1,'category','product/category/index',null,'',1,0,'C','0','0','product:category:list','#','admin','2024-11-04 03:48:55','',null,'商品分类菜单');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类查询',2000,1,'#','',null,'',1,0,'F','0','0','product:category:query','#','admin','2024-11-04 03:48:55','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类新增',2000,2,'#','',null,'',1,0,'F','0','0','product:category:add','#','admin','2024-11-04 03:48:55','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类修改',2000,3,'#','',null,'',1,0,'F','0','0','product:category:edit','#','admin','2024-11-04 03:48:55','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类删除',2000,4,'#','',null,'',1,0,'F','0','0','product:category:remove','#','admin','2024-11-04 03:48:55','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品分类导出',2000,5,'#','',null,'',1,0,'F','0','0','product:category:export','#','admin','2024-11-04 03:48:55','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库',4,1,'spu','product/spu/index',null,'',1,0,'C','0','0','system:spu:list','#','admin','2024-11-08 06:44:54','',null,'商品spu菜单');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库查询',2006,1,'#','',null,'',1,0,'F','0','0','system:spu:query','#','admin','2024-11-08 06:44:54','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库新增',2006,2,'#','',null,'',1,0,'F','0','0','system:spu:add','#','admin','2024-11-08 06:44:54','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库修改',2006,3,'#','',null,'',1,0,'F','0','0','system:spu:edit','#','admin','2024-11-08 06:44:54','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库删除',2006,4,'#','',null,'',1,0,'F','0','0','system:spu:remove','#','admin','2024-11-08 06:44:54','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品库导出',2006,5,'#','',null,'',1,0,'F','0','0','system:spu:export','#','admin','2024-11-08 06:44:54','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息',4,1,'customer','partner/customer/index',null,'',1,0,'C','0','0','partner:customer:list','#','admin','2024-11-11 01:45:58','',null,'客户信息菜单');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息查询',2012,1,'#','',null,'',1,0,'F','0','0','partner:customer:query','#','admin','2024-11-11 01:45:58','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息新增',2012,2,'#','',null,'',1,0,'F','0','0','partner:customer:add','#','admin','2024-11-11 01:45:58','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息修改',2012,3,'#','',null,'',1,0,'F','0','0','partner:customer:edit','#','admin','2024-11-11 01:45:58','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息删除',2012,4,'#','',null,'',1,0,'F','0','0','partner:customer:remove','#','admin','2024-11-11 01:45:58','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('客户信息导出',2012,5,'#','',null,'',1,0,'F','0','0','partner:customer:export','#','admin','2024-11-11 01:45:58','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息',4,1,'sku','product/sku/index',null,'',1,0,'C','0','0','product:sku:list','#','admin','2024-11-11 06:23:24','',null,'商品信息菜单');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息查询',2025,1,'#','',null,'',1,0,'F','0','0','product:sku:query','#','admin','2024-11-11 06:23:24','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息新增',2025,2,'#','',null,'',1,0,'F','0','0','product:sku:add','#','admin','2024-11-11 06:23:24','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息修改',2025,3,'#','',null,'',1,0,'F','0','0','product:sku:edit','#','admin','2024-11-11 06:23:24','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息删除',2025,4,'#','',null,'',1,0,'F','0','0','product:sku:remove','#','admin','2024-11-11 06:23:24','',null,'');
INSERT INTO `sys_menu` (`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`route_name`,`is_frame`,`is_cache`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES ('商品信息导出',2025,5,'#','',null,'',1,0,'F','0','0','product:sku:export','#','admin','2024-11-11 06:23:24','',null,'');

-- add dict type & data
INSERT INTO `sys_dict_type` (`dict_id`,`dict_name`,`dict_type`,`status`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (100,'业务是否','biz_yes_no','0','admin','2024-11-08 07:06:37','',null,null);
INSERT INTO `sys_dict_type` (`dict_id`,`dict_name`,`dict_type`,`status`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (101,'客户类型','t_customer_type','0','admin','2024-11-11 02:45:59','',null,null);
INSERT INTO `sys_dict_type` (`dict_id`,`dict_name`,`dict_type`,`status`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (102,'商品单位','t_sku_unit','0','admin','2024-11-11 08:12:35','',null,null);
