-- ============================================================
-- S1-2 菜单/权限：别名与映射（全局别名、客户SKU映射、临时商品）
-- 父菜单挂载在"基础信息"(menu_id=4) 下；menu_id 从 2050 起，避开现有最大值 2047
-- ============================================================

-- 父菜单（C）：别名与映射
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2050, '别名与映射', 4, 2, 'aliasMapping', 'product/aliasMapping/index', NULL, '', 1, 0, 'C', '0', '0', 'product:aliasMapping:list', '#', 'admin', sysdate(), '', NULL, '别名与映射菜单');

-- 按钮（F）：全局别名
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2051, '别名新增', 2050, 1, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:alias:add', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2052, '别名修改', 2050, 2, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:alias:edit', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2053, '别名删除', 2050, 3, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:alias:remove', '#', 'admin', sysdate(), '', NULL, '');

-- 按钮（F）：客户SKU映射
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2054, '映射新增', 2050, 4, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:mapping:add', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2055, '映射修改', 2050, 5, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:mapping:edit', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2056, '映射删除', 2050, 6, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:mapping:remove', '#', 'admin', sysdate(), '', NULL, '');

-- 按钮（F）：临时商品
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2057, '临时商品新增', 2050, 7, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:temp:add', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2058, '临时商品修改', 2050, 8, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:temp:edit', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2059, '临时商品删除', 2050, 9, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:temp:remove', '#', 'admin', sysdate(), '', NULL, '');
INSERT INTO `sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `route_name`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2060, '临时商品转正', 2050, 10, '#', '', NULL, '', 1, 0, 'F', '0', '0', 'product:temp:convert', '#', 'admin', sysdate(), '', NULL, '');
